# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [12]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr + arr  #Both array shape must be same 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
# Also warning, but not an error instead infinity
1/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [10]:
arr**3 #raise to 3 (indices)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [13]:
Distance = np.array([10,20,30,45])
Time = np.array([0.50, 1.2, 3.00, 5.2])
Speed = Distance / Time
Speed

array([20.        , 16.66666667, 10.        ,  8.65384615])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [7]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [9]:
np.max(arr) #same as arr.max()

9

In [10]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [11]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [15]:
arrdata = np.array(([5,10,15],[20,25,30],[35,40,45]))
arrdata

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
arrdata + arrdata

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
data = arr.tolist()
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
arr1 = np.array(['prashant','arun'],dtype=)
arr2 = np.array(['nair','kumar'])
print(arr1)
print(arr2)

['prashant' 'arun']
['nair' 'kumar']


In [40]:
arr1 + arr2

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U6') dtype('<U6') dtype('<U6')

# Great Job!

That's all we need to know for now!